version: "3"

services:

  backend:
    build: ../
    restart: on-failure
    env_file:
      - config/backend/env
    networks:
      - pg_network
      - redis_network
      - nginx_network
    depends_on:
      - redis
      - postgresql

  redis:
    image: redis:alpine
    volumes:
      - redis_volume:/data
    networks:
      - redis_network

  postgresql:
    image: postgres:alpine
    volumes:
      - pg_volume:/var/lib/postgresql/data
    env_file:
      - config/postgresql/env
    networks:
      - pg_network

  nginx:
    image: nginx:alpine
    ports:
      - 8000:8000
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - nginx_network
    depends_on:
      - backend

networks:
  pg_network:
    driver: bridge
  redis_network:
    driver: bridge
  nginx_network:
    driver: bridge

volumes:
  pg_volume:
  redis_volume:
