# Generated by Django 2.2.4 on 2019-08-05 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения записи')),
                ('sent_amount', models.DecimalField(decimal_places=4, max_digits=24, verbose_name='Объем трансфера')),
                ('received_amount', models.DecimalField(decimal_places=4, max_digits=24, verbose_name='Объем трансфера')),
                ('commission_fee', models.DecimalField(decimal_places=4, max_digits=24, verbose_name='Размер комиссии')),
                ('from_acc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_transfers', to='accounts.Account')),
                ('to_acc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_transfers', to='accounts.Account')),
            ],
            options={
                'verbose_name': 'Переводы',
            },
        ),
    ]
