# Generated by Django 2.2.4 on 2019-08-05 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения записи')),
                ('currency', models.TextField(choices=[('USD', 'USD'), ('CNY', 'CNY'), ('EUR', 'EUR')], verbose_name='Валюта')),
                ('balance', models.DecimalField(decimal_places=4, default=0, max_digits=24, verbose_name='Текущий баланс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Счет',
            },
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(check=models.Q(balance__gte=0), name='positive_balance'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('user', 'currency')},
        ),
    ]
